import { Component, signal } from "@angular/core";
import { EventCard } from "./components/event-card/event-card";
import { Header } from "./layout/components/header/header";
import { Footer } from "./layout/components/footer/footer";
import { Hero } from "./components/hero/hero";

@Component({
    selector: "app-root",
    imports: [EventCard, Header, Footer, Hero],
    templateUrl: "./app.html",
    styleUrl: "./app.scss",
})
export class App {
    protected readonly title = signal("oser-bouger");
    data = {
        total_count: 2708,
        results: [
            {
                id: "11022",
                event_id: 4287,
                url: "https://www.paris.fr/evenements/les-balades-guidees-virtuelles-d-explore-paris-11022",
                title: "Les balades guid\u00e9es virtuelles d'Explore Paris",
                lead_text:
                    "Se balader dans les rues de Paris, y voir les fr\u00e8res M\u00e9li\u00e8s, visiter l\u2019int\u00e9rieur des canaux ou entendre les cris oubli\u00e9s des camelots, admirer les tr\u00e9sors de l\u2019Art Nouveau ou de Le Corbusier, faire un tour dans \u00ab\u00a0little india\u00a0\u00bb ou le \u00ab\u00a0Paris russe\u00a0\u00bb, devenir incollable sur le street art et surtout \u00e9changer en \u00ab\u00a0live\u00a0\u00bb avec un guide conf\u00e9rencier\u00a0!",
                description:
                    '<p>Plus de 50 balades ou conf\u00e9rences virtuelles, en semaine ou en week-end, de 0\u20ac \u00e0 12\u20ac\u00a0!</p><p>Les visites virtuelles sont <strong>anim\u00e9es en direct </strong>par un guide professionnel qui vous commente et pr\u00e9sente depuis chez lui une s\u00e9rie de documents, photos, vid\u00e9os gr\u00e2ce \u00e0 un <strong>outil simple d\'utilisation</strong>. Ces visites virtuelles sont <strong>interactives</strong>, vous \u00eates invit\u00e9s \u00e0 r\u00e9agir et poser des questions au cours de la conf\u00e9rence. <br></br></p><p>Au programme\u00a0: Partez pour une exploration urbaine \u00e0 travers les oeuvres de <a href="https://exploreparis.com/fr/3511-lek-et-sowat-explorations-des-profondeurs-conference-virtuelle-n3.html">Lek et Sowat</a>, participer \u00e0 un <a href="https://exploreparis.com/fr/3529-festin-indien-un-voyage-gourmand-entre-paris-et-l-inde-balade-virtuelle.html">festin indien</a>, d\u00e9couvrez les \u0153uvres de <a href="https://exploreparis.com/fr/2989-visite-virtuelle-street-art-dans-le-marais.html" target="_blank">street art du Marais</a>\u00a0ou <a href="https://exploreparis.com/fr/2988-visite-virtuelle-street-art-13eme-arrondissement.html" target="_blank">dans le 13e </a>arrondissement, faites une vir\u00e9e virtuelle \u00e0 <a href="https://exploreparis.com/fr/2966-viree-romantique-a-la-nouvelle-athenes.html" target="_blank">la Nouvelle Ath\u00e8nes</a>, prenez la route pour <a href="https://exploreparis.com/fr/2993-en-route-pour-les-indes-a-la-courneuve.html" target="_blank">les Indes \u00e0 la Courneuve</a>, \u00e9coutez <a href="https://exploreparis.com/fr/3481-histoire-de-la-musique-noire-le-hip-hop-naissance-et-origines-conference-virtuelle-n5.html">l\'histoire du hip-hop</a> ou du <a href="https://exploreparis.com/fr/3486-histoire-de-la-musique-noire-le-deejaying-conference-virtuelle-n7.html">deejaying </a>Sans oublier des conf\u00e9rences virtuelles in\u00e9dites\u00a0: Portraits de <a href="https://exploreparis.com/fr/2967-les-femmes-qui-ont-fait-paris.html" target="_blank">femmes qui ont fait Paris</a>, la <a href="https://exploreparis.com/fr/2968-la-culture-noire-a-paris.html" target="_blank">culture noire \u00e0 Paris</a>, la vie et les \u0153uvres de <a href="https://exploreparis.com/fr/3000-oscar-niemeyer-une-oeuvre-majeure-conference-virtuelle.html" target="_blank">l\'architecte Oscar Niemeyer</a>, l\'<a href="https://exploreparis.com/fr/2992-palais-justice-paris-visite-virtuelle.html" target="_blank">ancien Palais de justice de Paris.</a>.. Et plein d\'autres\u00a0! La diversit\u00e9 des visites propos\u00e9es ouvre un large spectre pour d\u00e9couvrir ou red\u00e9couvrir le Grand Paris sous des angles souvent in\u00e9dits\u00a0: celui du patrimoine insolite, du street art, de l\u2019architecture, des communaut\u00e9s, de l\u2019Egypte, des quartiers, de la femme, des mythes et l\u00e9gendes\u2026 <br></br></p><p>D\u00e9couvrez<a href="https://exploreparis.com/fr/30-virtuel" target="_blank" rel="noopener noreferrer"> toutes les conf\u00e9rences et visites virtuelles propos\u00e9es sur #ExploreParis. </a></p><p>Imagin\u00e9es lors du confinement de mars-avril 2020, les balades et visites virtuelles sont un <strong>soutien aux guides particuli\u00e8rement touch\u00e9s par la crise</strong>, et une nouvelle fa\u00e7on de montrer la m\u00e9tropole aux visiteurs du Grand Paris. En effet, contraints de se r\u00e9inventer par les effets de la crise sanitaire, les guides ont mis en place une offre de visites virtuelles, soit une adaptation virtuelles de leurs parcours habituels, soit des conf\u00e9rences virtuelles in\u00e9dites. <br></br></p><p><a href="https://exploreparis.com/fr/30-virtuel" target="_blank" rel="noopener noreferrer">#ExploreParis</a>, 1ere plateforme de visites guid\u00e9es virtuelles\u00a0!</p>',
                date_start: null,
                date_end: null,
                occurrences: null,
                date_description: null,
                cover_url:
                    "https://cdn.paris.fr/qfapv4/2021/11/08/huge-1348d72457dab352b952687963b8f2cd.jpg",
                cover_alt: "visites virtuelles d'Explore Paris",
                cover_credit: "Explore Paris",
                locations: [
                    {
                        accessibility: {
                            blind: null,
                            pmr: null,
                            deaf: null,
                            sign_language: null,
                            mental: null,
                        },
                        address_street: "Grand Paris",
                        address_zipCode: "75000",
                        address_details: null,
                        address_name: "Explore Paris",
                        address_lat_lon: "0.0,0.0",
                        location_type: "address",
                        address_city: "Grand Paris",
                    },
                ],
                address_name: "Explore Paris",
                address_street: "Grand Paris",
                address_zipcode: "75000",
                address_city: "Grand Paris",
                lat_lon: {
                    lon: 0.0,
                    lat: 0.0,
                },
                pmr: null,
                blind: null,
                deaf: null,
                sign_language: null,
                mental: null,
                transport: null,
                contact_url: "https://exploreparis.com/fr/",
                contact_phone: null,
                contact_mail: "contact@exploreparis.fr",
                contact_facebook: null,
                contact_twitter: null,
                price_type: "payant",
                price_detail: "De 0\u20ac \u00e0 12\u20ac",
                access_type: "obligatoire",
                access_link: "https://exploreparis.com/fr/30-virtuel",
                access_link_text: null,
                updated_at: "2021-11-08T20:10:54+00:00",
                image_couverture: null,
                programs: null,
                address_url: null,
                address_url_text: null,
                address_text: null,
                title_event: "Les balades guid\u00e9es virtuelles d'Explore Paris",
                audience: "Tout public.",
                childrens: null,
                group: "Agenda",
                locale: "fr",
                rank: 0.0,
                weight: 1,
                qfap_tags: "Balade urbaine",
                universe_tags: null,
                event_indoor: 1,
                event_pets_allowed: 0,
                contact_organisation_name: null,
                contact_url_text: "Explore Paris",
                contact_vimeo: null,
                contact_deezer: null,
                contact_tiktok: null,
                contact_twitch: null,
                contact_spotify: null,
                contact_youtube: null,
                contact_bandcamp: null,
                contact_linkedin: null,
                contact_snapchat: null,
                contact_whatsapp: null,
                contact_instagram: null,
                contact_messenger: null,
                contact_pinterest: null,
                contact_soundcloud: null,
                univers: null,
            },
            {
                id: "15396",
                event_id: 8604,
                url: "https://www.paris.fr/evenements/paroles-d-adultes-regards-d-enfants-aborder-la-crise-climatique-avec-les-jeunes-15396",
                title: "Paroles d\u2019adultes, regards d\u2019enfants\u00a0: aborder la crise climatique avec les jeunes",
                lead_text:
                    "Comment parler de la crise climatique avec nos enfants\u00a0? Comment passer de l\u2019anxi\u00e9t\u00e9 \u00e0 l\u2019action\u00a0? A l\u2019Acad\u00e9mie du Climat nous avons des r\u00e9ponses, venez les d\u00e9couvrir\u00a0!",
                description:
                    '<p><br><br><strong>POUR LES ENFANTS\u00a0: </strong>le samedi 22 janvier, en famille ou en autonomie, plein d\u2019ateliers pour faire d\u00e9couvrir aux enfants des solutions qui contribuent \u00e0 la transition \u00e9cologique. <br><br>Venez aussi d\u00e9couvrir les deux premiers cycles projets de <a href="https://www.academieduclimat.paris/evenements/ecole-du-climat-tumo-paris-4-portes-ouvertes/" target="_blank">TUMO Paris 4\u00a0L\u2019\u00e9cole du Climat</a><br><br><strong>POUR LES ADULTES, PARENTS ET ENSEIGNANTS\u00a0:</strong> rencontres, d\u00e9bats, groupe de paroles pour s\u2019interroger collectivement sur la p\u00e9dagogie et la transition \u00e9cologique. Des ateliers encadr\u00e9s sont propos\u00e9s \u00e0 vos enfants sur les temps d\u2019\u00e9changes du samedi entre adultes.<br><br><em><strong>Et la Buvette est ouverte toute la journ\u00e9e, pour se d\u00e9salt\u00e9rer ou pour une petite faim, \u00e0 l\u2019int\u00e9rieur ou dans la cour\u00a0!</strong></em></p><h2>SAMEDI 22 JANVIER</h2><p><strong>POUR TOUS EN FAMILLE OU EN AUTONOMIE </strong></p><p>10h-18h\u00a0: exposition <a href="https://www.academieduclimat.paris/evenements/exposition-photoclimat/" target="_blank" rel="noopener">PhotoClimat</a> (sans inscription)</p><p>10h-17h Atelier\u00a0\u2013 <a href="https://www.academieduclimat.paris/evenements/theatre-interactif/">Th\u00e9\u00e2tre interactif</a></p><p>de 14h \u00e0 18h\u00a0: <a href="https://www.academieduclimat.paris/evenements/looplab-transforme-tes-dechets-plastiques-en-objets-recycles/">Looplab transforme tes d\u00e9chets plastiques</a> (sans inscription)</p><p>14h-17h\u00a0: Atelier\u00a0\u2013 <a href="https://www.academieduclimat.paris/evenements/atelier-fresque-du-climat-kids/" target="_blank">Fresque du climat Kids</a></p><p>14h-16h\u00a0: D\u00e9monstration atelier <a href="https://www.academieduclimat.paris/evenements/le-climat-en-bouteille/" target="_blank" rel="noopener">\u2013 le climat en bouteille</a> (sans inscription)</p><p>14h-16h\u00a0: Atelier\u00a0\u2013 <a href="https://www.academieduclimat.paris/evenements/viens-coudre-ton-tote-bag-avec-tiercee/">Viens coudre ton tote bag </a></p><p>14h-15h30\u00a0: Atelier\u00a0\u2013 <a href="https://www.academieduclimat.paris/evenements/cuisinons/">Cours de cuisine v\u00e9</a><a href="https://www.academieduclimat.paris/evenements/cuisinons/" target="_blank">g\u00e9tarienne\u00a0!</a></p><p>14h-15h30\u00a0: Atelier\u00a0\u2013 <a href="https://www.academieduclimat.paris/evenements/velo-atelier-dinitiation/" target="_blank">Viens apprendre \u00e0 r\u00e9parer un v\u00e9lo</a></p><p>14h-15h30\u00a0: Atelier\u00a0\u2013 <a href="https://www.academieduclimat.paris/evenements/up-cycling-couture-_-atelier-dinitiation/" target="_blank">Up-cycling et initiation \u00e0 la couture</a></p><p>15h-17h\u00a0: Atelier-<a href="https://www.academieduclimat.paris/evenements/inventons-nos-vies-bas-carbone-kids/" target="_blank"> Inventons nos vies bas carbone Kids d\u00e8s 9 ans</a></p><p>16h-17h30\u00a0: Atelier\u00a0\u2013 <a href="https://www.academieduclimat.paris/evenements/cuisinons/">Cours de cuisine v\u00e9</a><a href="https://www.academieduclimat.paris/evenements/cuisinons/" target="_blank">g\u00e9tarienne\u00a0!</a></p><p>16h-17h30\u00a0: Atelier\u00a0\u2013 <a href="https://www.academieduclimat.paris/evenements/velo-atelier-dinitiation/" target="_blank">Viens apprendre \u00e0 r\u00e9parer un v\u00e9lo</a></p><p>16h-17h30\u00a0: Atelier\u00a0\u2013 <a href="https://www.academieduclimat.paris/evenements/up-cycling-couture-_-atelier-dinitiation/" target="_blank">Up-cycling et initiation \u00e0 la couture</a></p><p><strong>POUR LES PARENTS, LES EDUC\u2019, LES PROFS\u2026</strong><br><br>14h-15h30\u00a0: <strong>Groupe de parole \u201c<a href="https://www.academieduclimat.paris/evenements/groupe-de-parole-crise-climatique-comment-en-parler-aux-enfants-et-aux-jeunes-sans-effrayer/" target="_blank">Crise climatique\u00a0: comment en parler aux enfants sans les effrayer\u00a0?\u201d</a></strong><br>16h-17h30\u00a0: <strong>Conf\u00e9rence <a href="https://www.academieduclimat.paris/evenements/conference-parler-aux-enfants-et-aux-jeunes-de-crise-climatique-y-a-t-il-une-recette-magique/" target="_blank">\u201cParler aux enfants et aux jeunes de la crise climatique\u00a0: une recette magique\u00a0?\u201d </a><br><br><br>Et le mercredi 26 janvier pour les \u00e9duc et les profs\u2026</strong><br><br>14h-15h30\u00a0: <strong>Conf\u00e9rence \u201c<strong><a href="https://www.academieduclimat.paris/evenements/conference-je-veux-enseigner-la-transition-ecologique-oui-mais-comment/" target="_blank">Je veux enseigner la transition \u00e9cologique\u00a0: oui mais comment\u00a0?</a>\u201d</strong> </strong>.<br>14h-15h30\u00a0: <strong>Conf\u00e9rence \u201c<a href="https://www.academieduclimat.paris/evenements/conference-ecoles-en-ville-comment-sensibiliser-les-enfants-a-la-nature/" target="_blank">\u00c9coles en ville\u00a0: comment sensibiliser les enfants \u00e0 la nature </a>?\u201d</strong></p><p>L\u2019ensemble de ces interventions et ateliers se d\u00e9roulent dans le cadre des journ\u00e9es d\u00e9di\u00e9es \u00e0 l\u2019\u00e9ducation et \u00e0 la transition \u00e9cologique organis\u00e9es par l\u2019Acad\u00e9mie du Climat autour de la journ\u00e9e internationale de l\u2019\u00e9ducation le 24 janvier 2022.</p>',
                date_start: null,
                date_end: null,
                occurrences: null,
                date_description: null,
                cover_url:
                    "https://cdn.paris.fr/qfapv4/2022/01/13/huge-edcf6fc585be822d71f064ff4cb66388.png",
                cover_alt: null,
                cover_credit: null,
                locations: [
                    {
                        accessibility: {
                            blind: null,
                            pmr: 1,
                            deaf: null,
                            sign_language: null,
                            mental: null,
                        },
                        address_street: "2 place Baudoyer",
                        address_zipCode: "75004",
                        address_details: "",
                        address_name: "Acad\u00e9mie du Climat",
                        address_lat_lon: "48.8561879931279,2.35569298377061",
                        location_type: "address",
                        address_city: "Paris",
                    },
                ],
                address_name: "Acad\u00e9mie du Climat",
                address_street: "2 place Baudoyer",
                address_zipcode: "75004",
                address_city: "Paris",
                lat_lon: {
                    lon: 2.35569298377061,
                    lat: 48.8561879931279,
                },
                pmr: 1,
                blind: null,
                deaf: null,
                sign_language: null,
                mental: null,
                transport: null,
                contact_url:
                    "https://www.academieduclimat.paris/evenements/paroles-dadultes-regards-denfants-aborder-la-crise-climatique-avec-les-jeunes/",
                contact_phone: null,
                contact_mail: null,
                contact_facebook: "https://www.facebook.com/academieduclimat",
                contact_twitter: "https://twitter.com/academieclimat",
                price_type: "gratuit",
                price_detail: null,
                access_type: null,
                access_link:
                    "https://adc-formulaires.paris.fr/adc/jsp/site/Portal.jsp?page=forms&view=stepView&id_form=1&init=true",
                access_link_text: null,
                updated_at: "2022-01-13T13:21:39+00:00",
                image_couverture: null,
                programs: null,
                address_url: null,
                address_url_text: null,
                address_text: null,
                title_event:
                    "Paroles d\u2019adultes, regards d\u2019enfants\u00a0: aborder la crise climatique avec les jeunes",
                audience: "Tout public.",
                childrens: null,
                group: "Aucun",
                locale: "fr",
                rank: 0.0,
                weight: 1,
                qfap_tags: null,
                universe_tags: null,
                event_indoor: 1,
                event_pets_allowed: 0,
                contact_organisation_name: null,
                contact_url_text: null,
                contact_vimeo: null,
                contact_deezer: null,
                contact_tiktok: null,
                contact_twitch: null,
                contact_spotify: null,
                contact_youtube: null,
                contact_bandcamp: null,
                contact_linkedin: null,
                contact_snapchat: null,
                contact_whatsapp: null,
                contact_instagram: null,
                contact_messenger: null,
                contact_pinterest: null,
                contact_soundcloud: null,
                univers: null,
            },
            {
                id: "85968",
                event_id: 66022,
                url: "https://www.paris.fr/evenements/la-vie-parisienne-85968",
                title: "La Vie Parisienne",
                lead_text: "Jacques Offenbach\r\nHenri Meilhac et Ludovic Hal\u00e9vi",
                description:
                    "<p>Cr\u00e9\u00e9e au Th\u00e9\u00e2tre du Palais-Royal, le 31 octobre 1866, <em>La Vie parisienne </em>conna\u00eet aussit\u00f4t un grand succ\u00e8s. Quelques semaines apr\u00e8s la premi\u00e8re, le couple imp\u00e9rial a d\u00e9couvert l\u2019\u0153uvre, tout comme le tsar de Russie, Alexandre II, alors en visite \u00e0 Paris pour l\u2019Exposition universelle. Les deux auteurs de <em>La Belle H\u00e9l\u00e8ne</em>, Henri Meilhac et Ludovic Hal\u00e9vy, n\u2019en sont plus \u00e0 leur coup d\u2019essai. Et le compositeur, Jacques Offenbach, sert \u00e0 nouveau le livret avec brio gr\u00e2ce \u00e0 des airs \u00e0 la fois enjou\u00e9s et audacieux. De surcro\u00eet, le th\u00e8me de cet op\u00e9ra bouffe est porteur\u00a0: tandis que l\u2019on vient d\u2019inaugurer la gare du Nord (1866), ou le Th\u00e9\u00e2tre du Ch\u00e2telet (1862), <em>La Vie parisienne </em>d\u00e9crit un quotidien o\u00f9 r\u00e8gne le plaisir\u00a0! Devenue ville- monde, la capitale qui rivalise avec Londres attire d\u00e9sormais les artistes, les hommes d\u2019affaires, mais aussi les touristes\u2026 et cet op\u00e9ra bouffe d\u00e9crit les rencontres, burlesques, entre ces diff\u00e9rents acteurs.</p><blockquote>\n  <p>Comme on le voit, le fond de la pi\u00e8ce n\u2019est rien; mais la fantaisie s\u2019y \u00e9tale, si abondante et si spirituelle, la musique est si alerte, si pimpante, si g\u00e9n\u00e9rale en son genre que La Vie parisienne a fait le tour du monde.</p>\n  <footer><cite><strong>Albert Vallin, \u00ab La Vie parisienne, Compte-rendu analytique \u00bb </strong>, Le Photo-Programme, Revue artistique illustr\u00e9e, IV, saison th\u00e9\u00e2trale 1896-1897.</cite></footer>\n</blockquote>\n<p><em>La</em> <em>Vie</em> <em>parisienne</em> est donc une photographie de la ville, de ses habitants et de leurs m\u0153urs \u00e0 la toute fin du Second Empire. Et si la capitale \u00e9merveille le touriste pour son art de la f\u00eate, le demi-monde, lui, sait se jouer du Tout-Paris. Rien de tout cela n\u2019aura \u00e9chapp\u00e9 aux auteurs qui, en jouant sur l\u2019inversion des r\u00f4les sociaux, d\u00e9crivent non sans causticit\u00e9, et parfois- m\u00eame avec s\u00e9v\u00e9rit\u00e9, la soci\u00e9t\u00e9 parisienne des ann\u00e9es 1860. Dans leur sillage, Val\u00e9rie Lesort \u00e0 la mise en sc\u00e8ne, accompagn\u00e9e par \u00c9ric Ruf \u00e0 la sc\u00e9nographie, Vanessa Sannino aux costumes et la troupe de la Com\u00e9die- Fran\u00e7aise observent ce pass\u00e9 \u00e0 l\u2019aune du temps pr\u00e9sent en jetant, \u00e0 leur tour, un regard \u00e0 la fois sympathique et critique sur la com\u00e9die humaine.</p><p><strong>Ce spectacle est propos\u00e9 dans le cadre du label Op\u00e9ra pour tous\u00a0!</strong></p><h4>SECRETS D\u2019UNE \u0152UVRE</h4><p>Pour en savoir plus sur <em>La Vie parisienne</em>, une pr\u00e9sentation du spectacle a lieu 45 minutes avant le d\u00e9but de la repr\u00e9sentation, au Salon Diaghilev, par Jean-Claude Yon, historien sp\u00e9cialiste de l\u2019op\u00e9ra au XIXe si\u00e8cle et Aur\u00e9lien Poidevin, responsable du contenu \u00e9ditorial du Th\u00e9\u00e2tre du Ch\u00e2telet, <strong>les mardi 16 et vendredi 19 juin, le mardi 23 juin, et le mardi 7 juillet 2026, \u00e0 18h45</strong> (Acc\u00e8s libre, r\u00e9serv\u00e9 aux d\u00e9tenteurs de billets pour la repr\u00e9sentation du jour).</p>",
                date_start: "2026-06-12T00:00:00+00:00",
                date_end: "2026-07-11T23:59:59+00:00",
                occurrences: null,
                date_description: "Du vendredi 12 juin 2026 au samedi 11 juillet 2026 : <br />",
                cover_url:
                    "https://cdn.paris.fr/qfapv4/2025/05/21/huge-1eb67fb6128c3f0bbd7c0a38c7d9ac57.jpg",
                cover_alt: "La Vie Parisienne au Ch\u00e2telet",
                cover_credit: "Thomas Amouroux",
                locations: [
                    {
                        address_street: "1 place du Ch\u00e2telet ",
                        address_zipCode: "75001",
                        address_name: "Th\u00e9\u00e2tre du Ch\u00e2telet",
                        address_lat_lon: "48.8576140063152,2.3467579588046",
                        location_type: "service",
                        address_city: "Paris",
                    },
                ],
                address_name: "Th\u00e9\u00e2tre du Ch\u00e2telet",
                address_street: "1 place du Ch\u00e2telet",
                address_zipcode: "75001",
                address_city: "Paris",
                lat_lon: {
                    lon: 2.3467579588046,
                    lat: 48.8576140063152,
                },
                pmr: null,
                blind: 1,
                deaf: null,
                sign_language: null,
                mental: null,
                transport: null,
                contact_url: "https://www.chatelet.com/programmation/25-26/la-vie-parisienne/",
                contact_phone: "+33140282840",
                contact_mail: "relation-publiques@chatelet.com",
                contact_facebook: "https://www.facebook.com/theatrechatelet",
                contact_twitter: null,
                price_type: "payant",
                price_detail: "<p>De 5 \u00e0 50 \u20ac</p>",
                access_type: "obligatoire",
                access_link: "https://www.chatelet.com/programmation/25-26/la-vie-parisienne/",
                access_link_text: "R\u00e9servation",
                updated_at: "2025-05-23T09:43:00+00:00",
                image_couverture: null,
                programs: null,
                address_url: null,
                address_url_text: null,
                address_text: null,
                title_event: null,
                audience: "Tout public.",
                childrens: null,
                group: "Aucun",
                locale: "fr",
                rank: 944.91,
                weight: 1,
                qfap_tags: "Spectacle musical",
                universe_tags: null,
                event_indoor: 1,
                event_pets_allowed: 0,
                contact_organisation_name: "Th\u00e9\u00e2tre du Ch\u00e2telet",
                contact_url_text: null,
                contact_vimeo: null,
                contact_deezer: null,
                contact_tiktok: null,
                contact_twitch: null,
                contact_spotify: null,
                contact_youtube: null,
                contact_bandcamp: null,
                contact_linkedin: null,
                contact_snapchat: null,
                contact_whatsapp: null,
                contact_instagram: "https://www.instagram.com/theatrechatelet/",
                contact_messenger: null,
                contact_pinterest: null,
                contact_soundcloud: null,
                univers: null,
            },
            {
                id: "79834",
                event_id: 60140,
                url: "https://www.paris.fr/evenements/la-culture-a-pleines-mains-79834",
                title: "La culture \u00e0 pleines mains",
                lead_text:
                    'Amoureux des mots et des signes\u00a0? \u00c0 Paris, cinq biblioth\u00e8ques vous ouvrent \u00e0 la richesse de la culture sourde. Poussez les portes des "P\u00f4les Sourds" et d\u00e9couvrez un monde de signes, de langues et de cultures, \u00e0 travers une programmation bilingue et \u00e9tonnante.',
                description:
                    '<p>Que vous soyez curieux, passionn\u00e9\nou en qu\u00eate de nouvelles exp\u00e9riences, venez participer aux \u00e9v\u00e9nements gratuits\nque les biblioth\u00e8ques "P\u00f4les Sourds" proposent tout au long de l\u2019ann\u00e9e\n:</p><ul><li><strong>Heures du conte\n bilingues</strong> pour les\n petits et les grands, o\u00f9 les histoires prennent vie en langue des signes\n fran\u00e7aise (LSF) et en fran\u00e7ais.</li><li><strong>Projections</strong> de films suivies\n d\u2019\u00e9changes conviviaux.</li><li><strong>Ateliers cr\u00e9atifs</strong>, pour apprendre,\n partager et s\u2019exprimer autrement.</li><li><strong>Conf\u00e9rences et\n rencontres</strong>, pour\n explorer des th\u00e9matiques vari\u00e9es et enrichir vos horizons.</li><li><strong>Spectacles\n vivants</strong> et <strong>expositions</strong>,\n qui c\u00e9l\u00e8brent la culture sourde et bien au-del\u00e0.</li></ul><p>Ici, la langue des signes est mise en lumi\u00e8re\nen tant que langue \u00e0 part enti\u00e8re, ouvrant de nouvelles fa\u00e7ons de communiquer,\nde partager la culture et de tisser des liens\u00a0!</p><p>Ces cinq biblioth\u00e8ques\n"P\u00f4les Sourds" existent depuis 2003. Elles sont uniques en leur genre\nen France et se sont affirm\u00e9es en mati\u00e8re d\u2019inclusion des personnes sourdes</p><p><br>\nElles offrent des collections sur la culture sourde, des ressources bilingues\nen langue des signes et en fran\u00e7ais et des services sp\u00e9cifiques pour tous. Leurs\n\u00e9quipes sont compos\u00e9es de biblioth\u00e9caires sourds, malentendants et entendants, form\u00e9s\n\u00e0 la langue des signes fran\u00e7aise.</p><p><strong>O\u00f9 nous trouver\u00a0?</strong></p><p>Cinq m\u00e9diath\u00e8ques au sein du r\u00e9seau municipal vous accueillent\u00a0:</p><ul><li><strong><a href="https://www.paris.fr/lieux/mediatheque-de-la-canopee-16634" target="_blank" rel="noopener" title="Ouverture dans un nouvel onglet">M\u00e9diath\u00e8que de la Canop\u00e9e</a> </strong>(1<sup>er</sup>)</li><li><strong><a href="https://www.paris.fr/lieux/bibliotheque-andre-malraux-1691" target="_blank" rel="noopener" title="Ouverture dans un nouvel onglet">Biblioth\u00e8que Andr\u00e9 Malraux</a></strong> (6e)</li><li><strong><a href="https://www.paris.fr/lieux/bibliotheque-louise-walser-gaillard-6094" target="_blank" rel="noopener" title="Ouverture dans un nouvel onglet">Biblioth\u00e8que Louise Walser-Gaillard</a> </strong>(9e)</li><li><strong><a href="https://www.paris.fr/lieux/bibliotheque-saint-eloi-1725" target="_blank" rel="noopener" title="Ouverture dans un nouvel onglet">Biblioth\u00e8que Saint-Eloi </a></strong>(12<sup>e</sup>)</li><li><strong><a href="https://www.paris.fr/lieux/mediatheque-james-baldwin-20205" target="_blank" rel="noopener" title="Ouverture dans un nouvel onglet">M\u00e9diath\u00e8que James Baldwin</a> </strong>(19<sup>e</sup>)</li></ul><p>Rejoignez-nous dans cette belle aventure, et laissez-vous surprendre par\nune offre culturelle unique \u00e0 Paris.</p>',
                date_start: "2025-01-01T00:00:00+00:00",
                date_end: "2026-12-31T23:59:59+00:00",
                occurrences: null,
                date_description:
                    "Du mercredi 01 janvier 2025 au jeudi 31 d\u00e9cembre 2026 : <br />",
                cover_url:
                    "https://cdn.paris.fr/qfapv4/2025/02/04/huge-bf8a4b90ed22a2f53c44c9d9ed2d180f.jpeg",
                cover_alt: "La culture \u00e0 pleines mains",
                cover_credit: "adonestock",
                locations: [
                    {
                        text: "Les Biblioth\u00e8ques de la Ville de Paris",
                        address_lat_lon: "48.856578,2.351828",
                        location_type: "text",
                    },
                ],
                address_name: null,
                address_street: null,
                address_zipcode: null,
                address_city: null,
                lat_lon: {
                    lon: 2.351828,
                    lat: 48.856578,
                },
                pmr: null,
                blind: null,
                deaf: null,
                sign_language: null,
                mental: null,
                transport: null,
                contact_url: null,
                contact_phone: null,
                contact_mail: null,
                contact_facebook: "https://www.facebook.com/bibliopi",
                contact_twitter: null,
                price_type: "gratuit",
                price_detail: null,
                access_type: "non",
                access_link: null,
                access_link_text: null,
                updated_at: "2025-08-05T15:18:34+00:00",
                image_couverture: null,
                programs:
                    "Soir\u00e9e jeux de soci\u00e9t\u00e9\u00a0! (https://www.paris.fr/evenements/soiree-jeux-de-societe-113637);Heure du conte - en fran\u00e7ais et en Langue des Signes Fran\u00e7aise (https://www.paris.fr/evenements/heure-du-conte-en-francais-et-en-langue-des-signes-francaise-113644)",
                address_url: null,
                address_url_text: null,
                address_text: "Les Biblioth\u00e8ques de la Ville de Paris",
                title_event: null,
                audience: "Tout public.",
                childrens:
                    'Bibliopi en f\u00eate 2025\u00a0! (https://www.paris.fr/evenements/bibliopi-en-fete-2025-82705);Conf\u00e9rence " L\u2019\u00e9mergence naturelle des langues des signes dans la famille au Br\u00e9sil avec Ivani Souza-Fuselier, chercheuse, suivi du t\u00e9moignage \u00ab\u00a0la privation de Langue des signes\u00a0\u00bb de C\u00e9dric Cannone, sourd fran\u00e7ais" (https://www.paris.fr/evenements/conference-l-emergence-naturelle-des-langues-des-signes-dans-la-famille-au-bresil-avec-ivani-souza-fuselier-chercheuse-suivi-du-temoignage-la-privation-de-langue-des-signes-de-cedric-cannone-sourd-francais-82441);Orthosigneuse, un m\u00e9tier \u00e0 d\u00e9couvrir\u00a0: rencontre avec Saliha Heoua\u00efne (https://www.paris.fr/evenements/orthosigneuse-un-metier-a-decouvrir-rencontre-avec-saliha-henouaine-111599);Club des fans (LSF/FR) (https://www.paris.fr/evenements/club-des-fans-lsf-fr-76285);Projection "Rom\u00e9o et Kristina" de Nicolas Hans-Martin (https://www.paris.fr/evenements/projection-romeo-et-kristina-de-nicolas-hans-martin-81937);Femmes artistes oubli\u00e9es de l\'histoire de l\'art\u00a0: balade urbaine (https://www.paris.fr/evenements/femmes-artistes-oubliees-de-l-histoire-de-l-art-jeu-de-piste-et-balade-urbaine-74809);"Deux"\u00a0: spectacle de danse en Langue des Signes Fran\u00e7aise et en fran\u00e7ais\u00a0! - COMPLET (https://www.paris.fr/evenements/2-spectacle-de-danse-en-langue-des-signes-francaise-et-en-francais-77595);Atelier de danse tout terrain LSF/FR\u00a0: comment les lieux nous font danser (https://www.paris.fr/evenements/atelier-de-danse-tout-terrain-lsf-fr-comment-les-lieux-nous-font-danser-76517);COMPLET\u00a0! // Atelier de danse flamenco LSF/FR (https://www.paris.fr/evenements/atelier-de-danse-flamenco-lsf-fr-81010);Table-ronde "Femmes et libert\u00e9s\u00a0: Entre r\u00e9sistances et exil" (https://www.paris.fr/evenements/table-ronde-femmes-et-libertes-entre-resistances-et-exil-80453);Nos rendez-vous litt\u00e9raires\u00a0: Plume \u00e0 la page (https://www.paris.fr/evenements/cafe-des-lecteurs-14017);Heure du conte LSF/FR \u00e0 hauteur de b\u00e9b\u00e9s\u00a0! (https://www.paris.fr/evenements/heure-du-conte-lsf-fr-a-hauteur-de-bebes-42633);COMPLET // La Singla\u00a0: soir\u00e9e cin\u00e9ma (https://www.paris.fr/evenements/la-singla-soiree-cinema-81065);Nos rendez-vous litt\u00e9raires\u00a0: Performance litt\u00e9raire (https://www.paris.fr/evenements/nos-rendez-vous-litteraires-performance-litteraire-113648);Nos rendez-vous litt\u00e9raires\u00a0: Plume \u00e0 la page (https://www.paris.fr/evenements/nos-rendez-vous-litteraires-plume-a-la-page-113640);J\'ai un coup de coeur\u2026 et vous\u00a0? (https://www.paris.fr/evenements/j-ai-un-coup-de-coeur-et-vous-57381);Le jardin se fait une beaut\u00e9 (https://www.paris.fr/evenements/le-jardin-se-fait-une-beaute-82727);Et si l\'on jouait\u00a0? (https://www.paris.fr/evenements/et-si-l-on-jouait-82728);Les biblioth\u00e9caires racontent et signent\u2026 pour les b\u00e9b\u00e9s (https://www.paris.fr/evenements/les-bibliothecaires-racontent-et-signent-pour-les-bebes-82776);Caf\u00e9 des parents "Mon enfant et les \u00e9crans" (https://www.paris.fr/evenements/cafe-des-parents-mon-enfant-et-les-ecrans-84056);Projection \u00ab\u00a0Retour \u00e0 Vi\u0161egrad\u00a0\u00bb de Julie Biro et Antoine Jaccoud (https://www.paris.fr/evenements/projection-retour-a-visegrad-de-julie-biro-et-antoine-jaccoud-83190);Projection "Levante" de Lillah Halla (https://www.paris.fr/evenements/projection-levante-de-lillah-halla-83198);Projections - Festival Silhouette (https://www.paris.fr/evenements/projections-festival-silhouette-83183);Conf\u00e9rence "\u00c0 vos cartes\u00a0! Exp\u00e9riences habitantes et cartographies du quartier" (https://www.paris.fr/evenements/conference-a-vos-cartes-experiences-habitantes-et-cartographies-du-quartier-83193);Journ\u00e9e internationale des droits des femmes\u00a0: rencontre avec les autrices Florence Medina et Chlo\u00e9 Lume (https://www.paris.fr/evenements/journee-internationale-des-droits-des-femmes-rencontre-avec-les-autrices-florence-medina-et-chloe-lume-78477);Rencontre avec Ketty Steward\u00a0: "Le Futur au Pluriel\u00a0: R\u00e9parer la science-fiction\u00a0?" (https://www.paris.fr/evenements/rencontre-avec-ketty-steward-le-futur-au-pluriel-reparer-la-science-fiction-78491);L\'Heure du conte 4-6 ans LSF/FR (https://www.paris.fr/evenements/heure-du-conte-bilingue-lsf-francais-11130);Et si l\'on jouait\u00a0? (https://www.paris.fr/evenements/et-si-l-on-jouait-81287);Et si l\'on jouait\u00a0? (https://www.paris.fr/evenements/et-si-l-on-jouait-81536);Quelle place pour les artistes sourds dans la soci\u00e9t\u00e9 d\'aujourd\'hui\u00a0?\u00a0: rencontre avec Jo\u00ebl Chalude (https://www.paris.fr/evenements/quelle-place-pour-les-artistes-sourds-dans-la-societe-d-aujourd-hui-rencontre-avec-joel-chalude-81297);Rencontre avec David Chavalarias "Faut-il quitter les r\u00e9seaux sociaux\u00a0?" (https://www.paris.fr/evenements/rencontre-avec-david-chavalarias-faut-il-quitter-les-reseaux-sociaux-80457);Animaux et Sourds\u00a0: discrimin\u00e9s par leur absence de parole\u00a0? (https://www.paris.fr/evenements/animaux-et-sourds-discrimines-par-leur-absence-de-parole-114917);Go\u00fbter des Mordus du manga\u00a0! LSF/FR (https://www.paris.fr/evenements/gouter-des-mordus-du-manga-lsf-fr-113647);Mon Premier Festival 2026\u00a0: Cin\u00e9-contes "Dans tous les sens"\u00a0! LSF/FR (https://www.paris.fr/evenements/mon-premier-festival-2026-cine-contes-dans-tous-les-sens-lsf-fr-114933);Spectacle jeunesse LSF/FR - "En forme\u00a0! en L.S.F" (https://www.paris.fr/evenements/spectacle-jeunesse-lsf-fr-en-forme-en-l-s-f-82279);Spectacle LSF/FR - "Les m\u00e9duses n\u2019ont pas d\u2019oreilles" (https://www.paris.fr/evenements/spectacle-lsf-fr-les-meduses-n-ont-pas-d-oreilles-82029);Soir\u00e9e jeux de r\u00f4le (https://www.paris.fr/evenements/soiree-jeux-de-role-82544);Le frou frou du cancan\u00a0: rencontre (https://www.paris.fr/evenements/le-frou-frou-du-cancan-rencontre-84007);Soir\u00e9e jeux de soci\u00e9t\u00e9\u00a0! (https://www.paris.fr/evenements/soiree-jeux-de-societe-29641);Po\u00e9sie et Langue des Signes Fran\u00e7aise\u00a0: lecture-rencontre (https://www.paris.fr/evenements/poesie-et-langue-des-signes-francaise-rencontre-77352);Spectacle \u00ab\u00a0po\u00e8mes du silence, suite\u2026\u00a0\u00bb avec Levent Beskardes et Aurore Corominas (https://www.paris.fr/evenements/spectacle-poemes-du-silence-suite-avec-levent-beskardes-et-aurore-corominas-78234);Club des fans (LSF/FR) (https://www.paris.fr/evenements/club-des-fans-lsf-fr-78277);Atelier num\u00e9rique\u00a0\u00e0 la carte (LSF/FR) (https://www.paris.fr/evenements/ateliers-numeriques-rdv-a-la-carte-11443);"Deux"\u00a0: spectacle de danse en Langue des Signes Fran\u00e7aise et en fran\u00e7ais\u00a0! (https://www.paris.fr/evenements/2-spectacle-de-danse-en-langue-des-signes-francaise-et-en-francais-76619);Service d\'\u00e9crivain public en Langue des Signes Fran\u00e7aise (LSF) (https://www.paris.fr/evenements/service-d-ecrivain-public-en-langue-des-signes-francaise-lsf-79003);Charlie Chaplin, un g\u00e9nie \u00e9pris de libert\u00e9 (https://www.paris.fr/evenements/charlie-chaplin-un-genie-epris-de-liberte-77933);Atelier de conversation en Langue des Signes Fran\u00e7aise (LSF) (https://www.paris.fr/evenements/atelier-de-conversation-en-lsf-11237);Conf\u00e9rence\u00a0: "Anciens signes et signes actuels\u00a0: la LSF en \u00e9volution" (https://www.paris.fr/evenements/conference-anciens-signes-et-signes-actuels-la-lsf-en-evolution-76293);Soir\u00e9e jeux (LSF/FR) (https://www.paris.fr/evenements/soiree-jeux-bilingue-11447);J\'ai un coup de c\u0153ur\u2026 et vous\u00a0? (https://www.paris.fr/evenements/copie-2-de-j-ai-un-coup-de-coeur-et-vous-77931);La place des Sourds dans l\'histoire du cin\u00e9ma\u00a0: rencontre avec Barbara Foug\u00e8re-Danezan (https://www.paris.fr/evenements/l-histoire-des-sourds-au-cinema-rencontre-avec-barbara-fougere-danezan-80046);Centenaire de James Baldwin - Projection et conf\u00e9rence (https://www.paris.fr/evenements/centenaire-de-james-baldwin-projection-et-conference-87127);F\u00eate de la musique - DJ Sets avec Lyl Radio (https://www.paris.fr/evenements/fete-de-la-musique-dj-sets-avec-lyl-radio-87360);[COMPLET] Concours de puzzle\u00a0: 500 et 1000 pi\u00e8ces (https://www.paris.fr/evenements/concours-de-puzzle-500-et-1000-pieces-87453);Les Racontines bilingues 0-3 ans LSF/FR (https://www.paris.fr/evenements/les-racontines-bilingues-francais-lsf-11122);Table ronde \u00ab\u00a0les enjeux de la traduction litt\u00e9raire en Langue des Signes Fran\u00e7aise\u00a0\u00bb (https://www.paris.fr/evenements/table-ronde-les-enjeux-de-la-traduction-litteraire-en-langue-des-signes-francaise-84408);Traduire le roman graphique en Langue des Signes Fran\u00e7aise\u00a0: rencontre avec Sandra Recollon (https://www.paris.fr/evenements/traduire-le-roman-graphique-en-langue-des-signes-francaise-rencontre-avec-sandra-recollon-88146);Les loups-garous sont de retour \u00e0 Saint-\u00c9loi\u00a0! (https://www.paris.fr/evenements/les-loups-garous-sont-de-retour-a-saint-eloi-50493);Les Heures du Conte - Bilingues LSF/FR (https://www.paris.fr/evenements/les-heures-du-conte-bilingues-lsf-fr-115004);Halloween aux manettes\u00a0: atelier jeu vid\u00e9o ados LSF/FR\u00a0! (https://www.paris.fr/evenements/halloween-aux-manettes-atelier-jeu-video-ados-lsf-fr-88334);Soir\u00e9e jeux (LSF/FR) (https://www.paris.fr/evenements/soiree-jeux-lsf-fr-88515);Samedi jeux (LSF/FR) (https://www.paris.fr/evenements/samedi-jeux-lsf-fr-88150);Des sourds dans l\'espace\u00a0: rencontre LSF/FR (https://www.paris.fr/evenements/des-sourds-dans-l-espace-rencontre-lsf-fr-88678);Spectacle "Les m\u00e9duses n\u2019ont pas d\u2019oreilles" [LSF/FR] (https://www.paris.fr/evenements/spectacle-les-meduses-n-ont-pas-d-oreilles-lsf-fr-88981);2 ateliers avec Pascale Pavy (https://www.paris.fr/evenements/2-ateliers-avec-pascale-pavy-89041);Table ronde\u00a0:"\u00catre jeune de quartier aujourd\u2019hui\u00a0: entre st\u00e9r\u00e9otypes et r\u00e9alit\u00e9" (https://www.paris.fr/evenements/table-ronde-la-banlieue-et-ses-grands-ensembles-entre-violence-solidarite-et-ressentiment-88607);JILS/JMS - Projection L\u2019\u0152il et la Main\u00a0\u2013 \u00ab\u00a0Marvin, des \u00e9toiles dans les yeux\u00a0\u00bb et table-ronde (https://www.paris.fr/evenements/jils-jms-projection-l-oeil-et-la-main-marvin-des-etoiles-dans-les-yeux-et-table-ronde-89189);Atelier jeux vid\u00e9o LSF/FR (https://www.paris.fr/evenements/numok-2022-apres-midi-jeux-videos-15327);Concours de puzzle LSF/FR \u00e0 Saint-\u00c9loi (https://www.paris.fr/evenements/concours-de-puzzle-lsf-fr-a-saint-eloi-89503);Mon Premier Festival 2025\u00a0: du cin\u00e9ma pour les petits gourmands \u00e0 Saint-\u00c9loi (https://www.paris.fr/evenements/mon-premier-festival-2025-du-cinema-pour-les-petits-gourmands-a-saint-eloi-88202);Go\u00fbter des ados LSF/FR\u00a0: sp\u00e9cial Mordus du manga\u00a0! (https://www.paris.fr/evenements/gouter-des-ados-special-manga-29237);L\'Arbre \u00e0 contes en Langue des Signes Fran\u00e7aise et en fran\u00e7ais (https://www.paris.fr/evenements/l-arbre-a-contes-60523);COMPLET\u00a0! Atelier calendrier de l\'Avent LSF/FR (https://www.paris.fr/evenements/atelier-calendrier-de-l-avent-lsf-fr-90635);Conf\u00e9rence "TDAH, mythe ou r\u00e9alit\u00e9\u00a0?" (https://www.paris.fr/evenements/conference-tdah-mythe-ou-realite-88606);Caf\u00e9 Signes & Jeux en LSF - S\u00e9niors et pour tous.tes (https://www.paris.fr/evenements/cafe-signes-jeux-seniors-et-pour-tous-tes-91544);"Nemchou, la libert\u00e9 \u00e0 port\u00e9e de main" projection du film suivi d\'un d\u00e9bat (https://www.paris.fr/evenements/projection-du-film-nemchou-la-liberte-a-portee-de-main-suivi-d-un-debat-91626);Conf\u00e9rence \u00ab\u00a0Pauline, apicultrice sourde \u00e0 l\u2019\u00e9coute des abeilles\u00a0\u00bb (https://www.paris.fr/evenements/conference-pauline-apicultrice-sourde-a-l-ecoute-des-abeilles-92135);Et si l\'on jouait\u00a0? (https://www.paris.fr/evenements/et-si-l-on-jouait-92588);J\'ai un coup de c\u0153ur\u2026 et vous\u00a0? (https://www.paris.fr/evenements/j-ai-un-coup-de-coeur-et-vous-99176);Conf\u00e9rence "Histoire de l\u2019Image anim\u00e9e\u00a0\u2013 De la pr\u00e9histoire \u00e0 la 3D" (https://www.paris.fr/evenements/conference-histoire-de-l-image-animee-de-la-prehistoire-a-la-3d-89213);Et si l\'on jouait \u00e0 des jeux GEANTS\u00a0? (https://www.paris.fr/evenements/et-si-l-on-jouait-a-des-jeux-geants-92587);A la d\u00e9couverte de Downstairs\u00a0: le nouveau jeu de Art\'Sign (https://www.paris.fr/evenements/a-la-decouverte-de-downstairs-le-nouveau-jeu-de-art-sign-99728);Cycle "Que se passe-t-il\u00a0?" - Conf\u00e9rence "Paris bouge-t-il\u00a0? Paroles habitantes" (https://www.paris.fr/evenements/cycle-que-se-passe-t-il-conference-paris-bouge-t-il-paroles-habitantes-98905);Et si l\'on jouait \u00e0 des jeux g\u00e9ants\u00a0! (https://www.paris.fr/evenements/et-si-l-on-jouait-a-des-jeux-geants-99866);Spectacle jeunesse "Le Prince Tigre\u201d avec l\'IVT (https://www.paris.fr/evenements/spectacle-jeunesse-le-prince-tigre-avec-l-ivt-100745);Atelier BD\u00a0: deviens apprenti dessinateur avec Nikesco (https://www.paris.fr/evenements/atelier-bd-deviens-apprenti-dessinateur-avec-nikesco-99727);Le super pouvoir des Sourds\u00a0: carte blanche \u00e0 l\'auteur Nikesco (https://www.paris.fr/evenements/le-super-pouvoir-des-sourds-carte-blanche-a-l-auteur-nikesco-99627);Amour de soi\u00a0: Nikesco rencontre la Caverne des BD (https://www.paris.fr/evenements/amour-de-soi-nikesco-rencontre-la-caverne-des-bd-99870);Un Sourd dans la ville\u00a0: exposition (https://www.paris.fr/evenements/un-sourd-dans-la-ville-exposition-99777);Nuit de la lecture\u00a0\u00e0 Saint-\u00c9loi\u00a0: inauguration de la carte blanche \u00e0 Nikesco (https://www.paris.fr/evenements/nuit-de-la-lecture-a-saint-eloi-inauguration-de-la-carte-blanche-a-nikesco-99874);Un tournoi de scrabble \u00e0 la biblioth\u00e8que\u00a0! (https://www.paris.fr/evenements/un-tournoi-de-scrabble-a-la-bibliotheque-101335);Caf\u00e9 des parents "Accompagner son enfant \u00e0 communiquer et \u00e0 s\u2019auto-d\u00e9fendre sans violence" (https://www.paris.fr/evenements/cafe-des-parents-accompagner-son-enfant-a-communiquer-et-a-s-auto-defendre-sans-violence-100746);Table-ronde "Les migrations face aux d\u00e9fis climatiques" par la revue Mondes & Migrations (https://www.paris.fr/evenements/table-ronde-les-migrations-face-aux-defis-climatiques-par-la-revue-mondes-migrations-100499);Rencontre avec Emmanuel Guibert - Nuits de la lecture\u00a0\u00e0 la m\u00e9diath\u00e8que James Baldwin (https://www.paris.fr/evenements/rencontre-avec-emmanuel-guibert-nuits-de-la-lecture-a-la-mediatheque-james-baldwin-101917);Et si l\'on jouait\u2026 aux jeux vid\u00e9o\u00a0? (https://www.paris.fr/evenements/et-si-l-on-jouait-aux-jeux-video-103178);J\'ai un coup de c\u0153ur\u2026 et vous\u00a0? (https://www.paris.fr/evenements/j-ai-un-coup-de-coeur-et-vous-103175);Et si l\'on jouait\u00a0? (https://www.paris.fr/evenements/et-si-l-on-jouait-103180);Soir\u00e9e jeux de soci\u00e9t\u00e9 biblioth\u00e8que Andr\u00e9 Malraux - biblioth\u00e8ques du 5e-6e (https://www.paris.fr/evenements/soiree-jeux-de-societe-bibliotheque-andre-malraux-bibliotheques-du-5e-6e-79269);Club des Fans (LSF/FR) (https://www.paris.fr/evenements/club-des-fans-lsf-fr-91638);"Jean-Henri Fabre, une vie \u00e0 observer la nature" - lectures pour les petits (LSF/FR) (https://www.paris.fr/evenements/jean-henri-fabre-homere-des-insectes-lectures-pour-les-petits-101785);\u00ab\u00a0La bipolarit\u00e9, c\u2019est quoi\u00a0?\u00a0\u00bb avec Simon Bertin, psychiatre \u00e0 la Salp\u00eatri\u00e8re, Mariana Alonso chercheur \u00e0 l\'Institut Pasteur, Marie Giraud sourde-bipolaire. (https://www.paris.fr/evenements/la-bipolarite-c-est-quoi-avec-simon-bertin-psychiatre-a-la-salpetriere-mariana-alonso-chercheur-a-l-institut-pasteur-marie-giraud-sourde-bipolaire-103873);Femmes et m\u00e9tamorphoses \u00e0 travers la LSF\u00a0: table ronde (https://www.paris.fr/evenements/femmes-et-metamorphoses-a-travers-la-lsf-table-ronde-99900);Les biblioth\u00e8ques du 12e font leur cin\u00e9ma\u00a0: Prix du Public Les Yeux Doc, 6e \u00e9dition (https://www.paris.fr/evenements/les-bibliotheques-du-12e-font-leur-cinema-prix-public-les-yeux-doc-51840);Conf\u00e9rence par Camille Roth "Sommes-nous enferm\u00e9s dans des bulles num\u00e9riques\u00a0?" (https://www.paris.fr/evenements/conference-par-camille-roth-sommes-nous-enfermes-dans-des-bulles-numeriques-104355);Conf\u00e9rence-d\u00e9bat "Sous emprise" avec Olivia Monge, psychologue (https://www.paris.fr/evenements/conference-debat-sous-emprise-avec-olivia-monge-psychologue-103923);Spectacle de contes de Praline Gay-Para\u00a0: "R\u00e9cits de mon \u00eele" [LSF et FR] (https://www.paris.fr/evenements/spectacle-de-contes-de-praline-gay-para-recits-de-mon-ile-lsf-et-fr-101828);Atelier Mosa\u00efque \u00e0 la mani\u00e8re de Space Invader [LSF et FR] (https://www.paris.fr/evenements/atelier-mosaique-a-la-maniere-de-space-invader-lsf-et-fr-101817);Venez f\u00eater les 10 ans de la m\u00e9diath\u00e8que (https://www.paris.fr/evenements/venez-feter-les-10-ans-de-la-mediatheque-105108);\u00c9diter les auteur\u00b7es sourd\u00b7es\u00a0: un m\u00e9tier fondamental pour visibiliser la langue et la culture sourdes (https://www.paris.fr/evenements/editer-les-auteur-es-sourd-es-un-metier-fondamental-pour-visibiliser-la-langue-et-la-culture-sourdes-105196);Atelier hors les murs\u00a0: Dessiner la danse avec Nikesco (https://www.paris.fr/evenements/atelier-hors-les-murs-dessiner-la-danse-avec-nikesco-104803);Stop aux Fake News\u00a0!\u00a0: rencontre-d\u00e9bat LSF/FR avec Lise Pressac et Lina Fourneau (https://www.paris.fr/evenements/stop-aux-fake-news-rencontre-debat-lsf-fr-avec-lise-pressac-et-lina-fourneau-104647);Soir\u00e9e Caf\u00e9-Crochet (LSF/FR) (https://www.paris.fr/evenements/soiree-cafe-crochet-lsf-fr-105866);"Jonathan Reith, un passionn\u00e9 de BD, manga et Comics" conf\u00e9rence d\'un libraire Sourd (https://www.paris.fr/evenements/conference-jonathan-un-passionne-de-bd-manga-et-comics-avec-jonathan-reith-libraire-sourd-106295);Les coups de coeur en BD, mangas, Comics de Jonathan Reith, libraire Sourd (https://www.paris.fr/evenements/les-coups-de-coeur-en-bd-mangas-comics-de-jonathan-reith-libraire-sourd-106294);F\u00eate du court-m\u00e9trage - Programme \u201cEn haut de l\'affiche\u201d (https://www.paris.fr/evenements/fete-du-court-metrage-programme-en-haut-de-l-affiche-106821);Spectacle LSF de Marc Lacourt \u00ab\u00a0Pourquoi un arbre est une poule\u00a0?\u00a0\u00bb Festival PULSE (https://www.paris.fr/evenements/spectacle-lsf-de-marc-lacourt-pourquoi-un-arbre-est-une-poule-festival-pulse-105666);Rencontre-d\u00e9dicace avec Yasmina Khadra\u00a0: COMPLET (https://www.paris.fr/evenements/rencontre-dedicace-avec-yasmina-khadra-105954);La Petite S\u00e9ance - Projections jeunesse (https://www.paris.fr/evenements/la-petite-seance-projections-jeunesse-88433);Bibliopi en f\u00eate 7 \u00ab\u00a0Secoue ton monde\u00a0!\u00a0\u00bb (https://www.paris.fr/evenements/bibliopi-en-fete-7-secoue-ton-monde-107816);Conf\u00e9rence LSF/FR sur L\'art \u00e0 travers les artistes sourds par Juliette Dalle (https://www.paris.fr/evenements/conference-lsf-fr-sur-l-art-sourd-par-juliette-dalle-108203);L\'Envers des fripes\u00a0: Rencontre avec Emmanuelle Durand et Marie Castagn\u00e9 (https://www.paris.fr/evenements/l-envers-des-fripes-rencontre-avec-emmanuelle-durand-et-marie-castagne-107120);Atelier cr\u00e9ation de badges LSF/FR (https://www.paris.fr/evenements/atelier-creation-de-badges-lsf-fr-108272);Visite street art du quartier des Halles avec Deaf Invader [LSF et FR] (https://www.paris.fr/evenements/visite-street-art-du-quartier-des-halles-avec-deaf-invader-lsf-et-fr-108287);Cr\u00e9a Fun (https://www.paris.fr/evenements/crea-fun-108335);La mode sourde existe-t-elle\u00a0? Table ronde LSF/FR (https://www.paris.fr/evenements/la-mode-sourde-existe-t-elle-table-ronde-lsf-fr-105473);Masculinit\u00e9s plurielles\u00a0: exposition avec le Fonds d\'Art Contemporain - Paris collections (https://www.paris.fr/evenements/masculinites-plurielles-exposition-avec-le-fonds-d-art-contemporain-paris-collections-107085);Les contes du nouveau monde (https://www.paris.fr/evenements/les-contes-du-nouveau-monde-108668);Les biblioth\u00e9caires racontent et signent (https://www.paris.fr/evenements/les-bibliothecaires-racontent-et-signent-108677);Et si l\'on chansignait\u00a0? (https://www.paris.fr/evenements/et-si-l-on-chansignait-108689);J\'ai un coup de c\u0153ur\u2026 et vous\u00a0? (https://www.paris.fr/evenements/j-ai-un-coup-de-coeur-et-vous-110259);Couture en famille avec l\'association YayeMaye (https://www.paris.fr/evenements/couture-en-famille-avec-l-association-yayemaye-110429);Projection adulte - Cin\u00e9-Club Silhouette (https://www.paris.fr/evenements/projection-adulte-cine-club-silhouette-110717);Concours de puzzle\u00a01000 pi\u00e8ces par \u00e9quipe de 4 en Langue des Signes Fran\u00e7aise (https://www.paris.fr/evenements/concours-de-puzzle-1000-pieces-par-equipe-de-4-en-langue-des-signes-francaise-110757)',
                group: "Biblioth\u00e8ques",
                locale: "fr",
                rank: 352.67,
                weight: 1,
                qfap_tags: "Conf\u00e9rence;Enfants;Loisirs",
                universe_tags: null,
                event_indoor: 1,
                event_pets_allowed: 0,
                contact_organisation_name:
                    'Les 5 biblioth\u00e8ques "P\u00f4les Sourds\u201d de Paris',
                contact_url_text: null,
                contact_vimeo: null,
                contact_deezer: null,
                contact_tiktok: null,
                contact_twitch: null,
                contact_spotify: null,
                contact_youtube: null,
                contact_bandcamp: null,
                contact_linkedin: null,
                contact_snapchat: null,
                contact_whatsapp: null,
                contact_instagram: "https://www.instagram.com/bibliopi.paris/",
                contact_messenger: null,
                contact_pinterest: null,
                contact_soundcloud: null,
                univers: null,
            },
        ],
    };
}
